spring:
  datasource:
    url: jdbc:mysql://localhost:3306/erp
    username: root
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: 07aadbb507fdf74a7b748de508ed943457391637fafcf3b7c48e384e8b56b5f9

logging:
  level:
    org.hibernate.SQL: INFO
    org.hibernate.type.descriptor.sql: TRACE
    com.app.salty.checklist: DEBUG
    org.springframework.web: DEBUG

server:
  port: 8081